apiVersion: v1
kind: Service
metadata:
  name: k8s-web-to-nginx
spec:
  type: ClusterIP
  selector:
    app: k8s-web-to-nginx
  ports:
    - port: 3333
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-to-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-web-to-nginx
  template:
    metadata:
      labels:
        app: k8s-web-to-nginx
    spec:
      containers:
        - name: k8s-web-to-nginx
          image: harunaga113/k8s-web-to-nginx:1.0.10
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-web-to-nginx
  namespace: default
spec:
  rules:
    - http:
        paths:
          - path: /auth/
            pathType: Prefix
            backend:
              service:
                name: k8s-web-to-nginx
                port:
                  number: 3333
